kind: pipeline
name: helm-check

steps:
- name: init
  image: alpine
  environment:
    KUBECONFIG:
      from_secret: KUBECONFIG_ENC
    CHART_NAME: drone
  volumes:
  - name: kubernetes-secrets
    path: /etc/kubernetes
  commands:
  - "echo $KUBECONFIG | base64 -d > /etc/kubernetes/config"
  - "ln -s $(pwd) /etc/kubernetes/$CHART_NAME"
  ## delete existing deployment if exists
  - "helm delete ${DRONE_REPO_NAME}-${DRONE_COMMIT_SHA:0:16} --purge --kubeconfig /etc/kubernetes/config | :"

- name: "helm lint and dry run"
  image: keyporttech/helm-builder:2.12.1-1
  environment:
    CHART_NAME: drone
  volumes:
  - name: kubernetes-secrets
    path: /etc/kubernetes
  commands:
  - "helm version --kubeconfig /etc/kubernetes/config"
  - "helm lint /etc/kubernetes/$CHART_NAME --kubeconfig /etc/kubernetes/config"
  - "helm install /etc/kubernetes/$CHART_NAME -n ${DRONE_REPO_NAME}-${DRONE_COMMIT_SHA:0:16} --namespace helm-test --dry-run --kubeconfig /etc/kubernetes/config"

- name: "verify install/update and test"
  image: keyporttech/helm-builder:2.12.1
  environment:
    CHART_NAME: drone
  volumes:
  - name: kubernetes-secrets
    path: /etc/kubernetes
  commands:
  - "helm install . -n ${DRONE_REPO_NAME}-${DRONE_COMMIT_SHA:0:16} --kubeconfig /etc/kubernetes/config"
  - "sleep 5"
  - "helm test ${DRONE_REPO_NAME}-${DRONE_COMMIT_SHA:0:16} --cleanup --kubeconfig /etc/kubernetes/config"
  - "helm update ${DRONE_REPO_NAME}-${DRONE_COMMIT_SHA:0:16} ."

- name: "cleanup"
  image: keyporttech/helm-builder:2.12.1
  commands:
  - "helm delete ${DRONE_REPO_NAME}-${DRONE_COMMIT_SHA:0:16} --purge"

# - name: publish
#   image: keyporttech/chart_publisher
#   environment:
#     CHART_NAME: drone_helm_chart
#   commands:
#   - publish
volumes:
- name: kubernetes-secrets
  temp: {}
