kind: pipeline
name: helm-check

steps:
- name: "helm lint"
  image: keyporttech/helm-builder:2.12.1-1
  commands:
  - "helm version"
  - "helm lint"

- name: "dry run"
  image: keyporttech/helm-builder:2.12.1
  commands:
  - "helm install . -n ${DRONE_REPO_NAME}-${DRONE_COMMIT_SHA} --namespace: helm-test --dry-run"

- name: "install"
  image: keyporttech/helm-builder:2.12.1
  commands:
  - "helm delete ${DRONE_REPO_NAME}-${DRONE_COMMIT_SHA} --purge"
  - "helm install . -n ${DRONE_REPO_NAME}-${DRONE_COMMIT_SHA}"

- name: "helm test"
  image: keyporttech/helm-builder:2.12.1
  commands:
  - "helm test ${DRONE_REPO_NAME}-${DRONE_COMMIT_SHA} --cleanup"

- name: "helm update"
  image: keyporttech/helm-builder:2.12.1
  commands:
  - "helm update ${DRONE_REPO_NAME}-${DRONE_COMMIT_SHA} ."

- name: "cleanup"
  image: keyporttech/helm-builder:2.12.1
  commands:
  - "helm delete ${DRONE_REPO_NAME}-${DRONE_COMMIT_SHA} --purge"

# - name: publish
#   image: keyporttech/chart_publisher
#   environment:
#     CHART_NAME: drone_helm_chart
#   commands:
#   - publish
