apiVersion: v1
kind: Service
metadata:
  name: {{ template "drone.fullname" . }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "drone.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    {{- if not (.Values.server.env.DRONE_SERVER_PORT) }}
    targetPort: 80
    {{ else }}
    targetPort: {{ .Values.server.env.DRONE_SERVER_PORT }}
    {{ end -}}
{{- if hasKey .Values.service "nodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  - name: grpc
    port: 9000
    targetPort: 9000
  selector:
    app: {{ template "drone.name" . }}
    release: {{ .Release.Name | quote }}
    component: server
